manifest:
  self:
    path: ruuvi.air
  remotes:
    - name: nrf
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      remote: nrf
      path: nrf
      revision: v2.9.2
      import: true
      clone-depth: 1
