/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.37.0
 * Product:       sen66
 * Model-Version: 1.1.0
 */
/*
 * Copyright (c) 2024, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SEN66_I2C_H
#define SEN66_I2C_H

#ifdef __cplusplus
extern "C" {
#endif

#include "sensirion_config.h"
#define SEN66_I2C_ADDR_6B 0x6b

typedef enum {
    SEN66_DEVICE_RESET_CMD_ID = 0xd304,
    SEN66_START_CONTINUOUS_MEASUREMENT_CMD_ID = 0x21,
    SEN66_STOP_MEASUREMENT_CMD_ID = 0x104,
    SEN66_GET_DATA_READY_CMD_ID = 0x202,
    SEN66_READ_MEASURED_VALUES_AS_INTEGERS_CMD_ID = 0x300,
    SEN66_PERFORM_FORCED_CO2_RECALIBRATION_CMD_ID = 0x6707,
    SEN66_GET_PRODUCT_NAME_CMD_ID = 0xd014,
    SEN66_GET_SERIAL_NUMBER_CMD_ID = 0xd033,
    SEN66_GET_VERSION_CMD_ID = 0xd000,
} SEN66_CMD_ID;

typedef struct voc_algorithm_tuning_parameters {
    int16_t index_offset;
    int16_t learning_time_offset_hours;
    int16_t learning_time_gain_hours;
    int16_t gating_max_duration_minutes;
    int16_t std_initial;
    int16_t gain_factor;
} voc_algorithm_tuning_parameters_t;

/**
 * @brief Initialize i2c address of driver
 *
 * @param[in] i2c_address Used i2c address
 *
 */
void sen66_init(uint8_t i2c_address);

/**
 * @brief sen66_device_reset
 *
 * Executes a reset on the device. This has the same effect as a power cycle.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_device_reset();

/**
 * @brief Start a continuous measurement (interval 1s)
 *
 * Starts a continuous measurement. After power up, wait at least 500 ms before
 * sending this command. After sending this command, wait at least 1100 ms
 * before reading measurements. This command is only available in idle mode. If
 * the device is already in any measure mode, this command has no effect.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_start_continuous_measurement();

/**
 * @brief Stop the continuous measurement
 *
 * Stops the measurement and returns to idle mode. After sending this command,
 * wait at least 1000 ms before starting a new measurement. If the device is
 * already in idle mode, this command has no effect.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_stop_measurement();

/**
 * @brief Check if data is ready to be read out from the sensor
 *
 * This command can be used to check if new measurement results are ready to
 * read. The data ready flag is automatically reset after reading the
 * measurement values.
 *
 * @param[out] padding Padding byte, always 0x00.
 * @param[out] data_ready True (0x01) if data is ready, False (0x00) if not.
 * When no measurement is running, False will be returned.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_data_ready(uint8_t* padding, bool* data_ready);

/**
 * @brief read measured values as integers.
 *
 * Returns the measured values. The command 0x0202 "Get Data Ready" can be
 * used to check if new data is available since the last read operation. If no
 * new data is available, the previous values will be returned again. If no data
 * is available at all (e.g. measurement not running for at least one second),
 * all values will be at their upper limit (0xFFFF for , 0x7FFF for ).
 *
 * @param[out] mass_concentration_pm1p0 Value is scaled with factor 10: PM1.0
 * [µg/m³] = value / 10 *Note: If this value is unknown, 0xFFFF is returned.*
 * @param[out] mass_concentration_pm2p5 Value is scaled with factor 10: PM2.5
 * [µg/m³] = value / 10 *Note: If this value is unknown, 0xFFFF is returned.*
 * @param[out] mass_concentration_pm4p0 Value is scaled with factor 10: PM4.0
 * [µg/m³] = value / 10 *Note: If this value is unknown, 0xFFFF is returned.*
 * @param[out] mass_concentration_pm10p0 Value is scaled with factor 10: PM10.0
 * [µg/m³] = value / 10 *Note: If this value is unknown, 0xFFFF is returned.*
 * @param[out] ambient_humidity Value is scaled with factor 100: RH [%] = value
 * / 100 *Note: If this value is unknown, 0x7FFF is returned.*
 * @param[out] ambient_temperature Value is scaled with factor 200: T [°C] =
 * value / 200 *Note: If this value is unknown, 0x7FFF is returned.*
 * @param[out] voc_index Value is scaled with factor 10: VOC Index = value / 10
 * *Note: If this value is unknown, 0x7FFF is returned.*
 * @param[out] nox_index Value is scaled with factor 10: NOx Index = value / 10
 * *Note: If this value is unknown, 0x7FFF is returned. During the first 10..11
 * seconds after power-on or device reset, this value will be 0x7FFF as well.*
 * @param[out] co2 CO2 concentration [ppm] *Note: If this value is unknown,
 * 0xFFFF is returned. During the first 5..6 seconds after power-on or device
 * reset, this value will be 0xFFFF as well.*
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_read_measured_values_as_integers(
    uint16_t* mass_concentration_pm1p0, uint16_t* mass_concentration_pm2p5,
    uint16_t* mass_concentration_pm4p0, uint16_t* mass_concentration_pm10p0,
    int16_t* ambient_humidity, int16_t* ambient_temperature, int16_t* voc_index,
    int16_t* nox_index, uint16_t* co2);

/**
 * @brief Perform Forced CO2 Recalibration
 *
 * Execute the forced recalibration (FRC) of the CO2 signal on the SCD4x sensor.
 * See the datasheet of the SCD41 sensor for details how the forced
 * recalibration shall be used.
 *
 * @param[in] target_co2_concentration Target CO2 concentration [ppm] of the
 * test setup.
 * @param[out] correction Correction value as received from the SCD [ppm CO2].
 * Offset is 0x8000, if the recalibration has failed this value is 0xFFFF.
 *
 * @note After power-on wait at least 1000 ms and after stopping a measurement
 * 600 ms before sending this command. This command is not available in measure
 * mode. The recalibration procedure will take about 500 ms to complete, during
 * which time no other functions can be executed.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t
sen66_perform_forced_co2_recalibration(uint16_t target_co2_concentration,
                                       uint16_t* correction);

/**
 * @brief sen66_get_product_name
 *
 * Gets the product name from the device.
 *
 * @param[out] product_name Null-terminated ASCII string containing the product
 * name. Up to 32 characters can be read from the device.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_product_name(uint8_t* product_name,
                               uint16_t product_name_size);

/**
 * @brief sen66_get_serial_number
 *
 * Gets the serial number from the device.
 *
 * @param[out] serial_number Null-terminated ASCII string containing the serial
 * number. Up to 32 characters can be read from the device.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_serial_number(uint8_t* serial_number,
                                uint16_t serial_number_size);

/**
 * @brief sen66_get_version
 *
 * Gets the version information for the hardware, firmware and communication
 * protocol.
 *
 * @param[out] firmware_major Firmware major version number.
 * @param[out] firmware_minor Firmware minor version number.
 * @param[out] firmware_debug Firmware debug state. If the debug state is set,
 * the firmware is in development.
 * @param[out] hardware_major Hardware major version number.
 * @param[out] hardware_minor Hardware minor version number.
 * @param[out] protocol_major Protocol major version number.
 * @param[out] protocol_minor Protocol minor version number.
 * @param[out] padding Padding byte, ignore this.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_version(uint8_t* firmware_major, uint8_t* firmware_minor,
                          bool* firmware_debug, uint8_t* hardware_major,
                          uint8_t* hardware_minor, uint8_t* protocol_major,
                          uint8_t* protocol_minor, uint8_t* padding);

/**
 * @brief sen66_set_temperature_offset
 *
 * Sets the temperature offset parameters.
 *
 * @param[in] offset Constant temperature offset scaled with factor 200
 * (T [°C] = value / 200).
 * @param[in] slope Normalized temperature offset slope scaled with factor 10000
 * (applied factor = value / 10000).
 * @param[in] time_constant The time constant determines how fast the new slope
 * and offset will be applied. After the specified value in seconds,
 * 63% of the new slope and offset are applied. A time constant of zero means
 * the new values will be applied immediately
 * (within the next measure interval of 1 second).
 * @param[in] slot The temperature offset slot to be modified.
 * Valid values are 0 .. 4. If the value is outside this range,
 * the parameters will not be applied.
 */
int16_t sen66_set_temperature_offset(int16_t offset, int16_t slope,
                                     uint16_t time_constant, uint16_t slot);

/**
 * @brief sen66_get_voc_algorithm_tuning_parameters
 *
 * Gets the VOC algorithm tuning parameters from the device.
 *
 * @param[out] p_tuning_params Pointer to the tuning parameters structure to be
 * filled.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_voc_algorithm_tuning_parameters(
    voc_algorithm_tuning_parameters_t* const p_tuning_params);

/**
 * @brief sen66_set_voc_algorithm_tuning_parameters
 *
 * Sets the VOC algorithm tuning parameters on the device.
 *
 * @param[in] p_tuning_params Pointer to the tuning parameters structure
 * containing the values to be set.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_set_voc_algorithm_tuning_parameters(
    const voc_algorithm_tuning_parameters_t* const p_tuning_params);

/**
 * @brief sen66_get_ambient_pressure
 *
 * Gets the ambient pressure value from the device.
 *
 * @param[out] p_pressure_hpa Pointer to the variable to store the pressure
 * value in hPa.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_ambient_pressure(uint16_t* p_pressure_hpa);

#define SEN66_AMBIENT_PRESSURE_MIN_HPA 700
#define SEN66_AMBIENT_PRESSURE_MAX_HPA 1200

/**
 * @brief sen66_set_ambient_pressure
 *
 * Sets the ambient pressure value on the device.
 *
 * @param[in] pressure_hpa Ambient pressure in hPa to be set.
 *      Valid input values are between 700 to 1200 hPa.
 *      The default value is 1013 hPa
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_set_ambient_pressure(const uint16_t pressure_hpa);

typedef struct sen66_voc_algorithm_state_t {
    uint16_t voc_state[4];
} sen66_voc_algorithm_state_t;

/**
 * @brief sen66_get_voc_algorith_state
 *
 * Gets the VOC algorithm state from the device.
 *
 * @param[out] p_state Pointer to the state structure to be filled.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t sen66_get_voc_algorithm_state(sen66_voc_algorithm_state_t* p_state);

/**
 * @brief sen66_set_voc_state
 *
 * Sets the VOC algorithm state on the device.
 *
 * @param[in] p_state Pointer to the state structure containing the values to
 * be set.
 *
 * @return error_code 0 on success, an error code otherwise.
 */
int16_t
sen66_set_voc_algorithm_state(const sen66_voc_algorithm_state_t* p_state);

#ifdef __cplusplus
}
#endif
#endif  // SEN66_I2C_H
